### ISSUE TITLE
Report exporting [1 week]

### ISSUE THREAD

**Issue by perrygeo** [Ecotrust/floodplain-restoration#8]
Include maps (will require mapserver or mapnik?), answers to all the questions, data viz, some verbage (word,  html, pdfs)

**Comment by rhodges** [comment]
Dataviz covered in main report page.
Maps are now gathered as static images from Google and posted at the bottom of a printer-friendly page if a user wants to print or make a pdf. Perhaps this will work for exporting pdfs later.
